Update oauth2 page to contain example of secrets injection
kafbat/ui-docs pull request #16
Opened 2024-08-06 21:39 UTC by eternityduck

When configuring kafka ui I faced a problem where I have to go through all docs to discover usage of secrets in oauth provider. I want to introduce this example so the newcomers can setup their secrets in oauth section much easier

2024-08-12 18:32 UTC, Haarolean requested changes

2024-08-12 18:32 UTC, Haarolean commented on configuration/authentication/oauth2.md
> +Fields like `clientId` and `clientSecret` can be passed as secret. You need to use the `existingSecret` variable with appropriate fields.
This should be a part of helm charts docs rather than oauth directly

2024-08-19 19:26 UTC, eternityduck commented
@Haarolean Moved section.

2024-09-19 23:53 UTC, Haarolean approved these changes

2024-09-19 23:53 UTC, merged

2024-09-19 23:53 UTC, Haarolean commented
Thank you!